services:
  puppeteer:
    # build: .
    image: whatwewant/puppeteer:latest
    ports:
      - 18080:8080
    environment:
      BROWSER_WS_ENDPOINT: ws://browserless:3000

  browserless:
    image: whatwewant/browserless-chrome:v1-0
